StackStorm-Exchange/ci

.circle/index.py

Pretty-print the index JSON. Will increase the filesize a bit, but the index will be more human-readable, and the diff will get better, too.

Prettify index

---

.circle/deployment
.circle/index.py

This pull request includes some improvements in the index generation code:
1. It always processes files on the disk in the same order and also sorts the resulting JSON data which is written to the file. This ensures that if we provide the same input data, the end result file (final `index.json`) will be the same and won't change.
2. Changes the file format a bit so the packs are stored under the "packs" key and introduces new top-level "metadata" key which includes various index level metadata. Right now it includes the timestamp when the file has been generated and a hash of all the content. Hash won't change if the input data is the same so people who mirror the index can use this attribute to detect changes.
I know this change breaks the current format, but I think it's more future …

Various improvements, index format change

---

.circle/deployment
.circle/semver.py

This PR makes CI create version tags for the commits where `version` in `pack.yaml` has been changed.
There's also a script that converts versions like `1` or `0.1` (the latter is common in st2contrib) to valid semver when creating tags. It won't be necessary in the future, since we already have semver validation for `pack.yaml`, but useful for contrib, since we're preserving history and adding tags retroactively.

Create version tags

---

utils/exchange-bootstrap.sh

755 is applied to all pack files on checkout, so we should do it here as well, otherwise git will ask users to commit circle.yml with changed permissions, which is sorta annoying.

Chmod circle.yml to 755

---

.circle/deployment
utils/pack_content.py

Scan for pack content and store the count in the index. Full content metadata is not stored, empty content types are excluded.

Store pack content count in index

---

tools/set_repo_description.sh
utils/exchange-bootstrap.sh

The title says it all.
In addition to setting Github repo description, it also sets website to https://exchange.stackstorm.org/.
Having description set will make pack discovery through search engines easier.
On a related note - I also wanted to set topics for each repo to match `keywords`, but it looks like there is no API available yet for new Github topics functionality.
Resolves #35.

Add script which sets pack repo description to match description from pack.yaml

---

utils/exchange-bootstrap.sh

You can't automatically set the repo description when bootstrapping a new repo. 
The script sets up a new blank repo. You can't then try to pull `pack.yaml` from that repo, before it's had anything merged.

removed broken change to set repo description

---

.circle/circle.yml.sample

Removed extra pip cache dir that causes these errors on CircleCI:
```circle.yml specified cache directory: /home/ubuntu/.pip-cache but it does not exist```
Will also need to be propagated to all exchange repos

removed extraneous pip cache dir

---

files/.gitignore.sample

We were ignoring any lib directory, but many packs include `./actions/lib` and sometimes `./sensors/lib`. So making the rule more specific to only ignore top-level `./lib` dirs.

Be more specific about which lib directory we ignore

---

.circle/Makefile

I thought it would be a good idea to print out test coverage and timings for unittests in packs similar to what's done in st2 core.
This change depends on st2 PR: https://github.com/StackStorm/st2/pull/3508
And also has supporting documentation here: https://github.com/StackStorm/st2docs/pull/535

Enabling test coverage and timing output for pack tests

---

utils/exchange-bootstrap.sh

Sending notifications to #community slack for every comment is a bit much. Just need it for issue & PR creation/closing.

Reduce Slack Spam

---

.circle/Makefile

We should use `--config=<config>` not `--config <config>`, according to the flake8 help.

Flake8 Config path

---

.circle/deployment

In some packs there is no `pack.yaml` in older git history. 
This causes problems in the deployment script when it attempts to pull out all `pack.yaml` versions, and the deployment fails.
This change should handle that situation gracefully.

handle missing pack.yaml

---

.circle/circle.yml.sample
.gitignore

This fixes using CircleCI local builds for StackStrom-Exchange packs, as during local builds the container does not have access to the SSH key from CircleCI and thus can't clone via SSH. Given that the repo is public it can instead be cloned via `git://` which does not prompt to accept a public key or require the SSH key.
- Change git clone to git protocol from ssh (Fixes: #56)
- Add a `.gitignore` file to exclude JetBrains IDE dir and emacs saves.

Use git protocol to clone ci repo in .circle/circle.yml.sample

---

.circle/Makefile
.circle/dependencies
.circle/test
.circleci/config.yml

This pull request improves the output generated during "Dependencies" and "Run Tests" steps which run on each Circle CI build.
We have two main steps inside our pack build workflow - one to install the dependencies and the other one to run all the various (lint) checks and pack tests.
Before this change we actually installed dependencies in two places - inside "dependencies" step and also inside "run tests" step.
This meant that "Run Tests" step produced a lot of dependency installation related output which made actual "valuable" lint check and test output hard to spot.
And not to mention that it was confusing that the dependencies were installed in multiple places.
I added a new Make target and left "all" target as is, because the idea is that you can also use this ``Makefile`` with your …

Reduce noise during "Run Tests" Circle CI build step

---

.circle/Makefile
.circle/circle.yml.sample
.circle/dependencies

This pull request adds support for running various lint checks and pack tests under Python 3.6 (in addition to Python 2.7).
In addition to new Python 3 checks, I also added new "compile" check for Python 2.7 and Python 3.6 job which verifies Python syntax in pack files is valid.
A couple of things to keep in mind:
1. For the time being, we will run those checks on all the packs, but won't consider Python 3.x check and test failures as fatal (aka failing the build).
This will allow us to identify "problematic" packs. The goal is to add new ``python_version`` attribute to ``pack.yaml`` file and utilize that attribute in CI to determine if pack supports Python 3. For packs which claim support for Python 3, build will fail if Python 3 checks fail, and for ones which don't, it wont (will open …

Add support for Python 3.x checks to pack Circle CI config

---

.circle/circle.yml.sample
.circle/exit_on_py3_checks

This pull request updates sample pack Circle CI config so Python 3 build failures as treated as fatal for any pack which claims Python 3 support in pack.yaml file.

Treat Python 3 check and test failures as fatal for packs which claim Python 3 support

---

.circle/requirements-pack-tests.txt
.circle/validate.py

* Use `yaml.safe_load` instead of `yaml.load`, just to avoid a warning.
* Install Mock v2.0.0 so CI can use [`Mock.assert_called_once`](https://github.com/testing-cabal/mock/blob/2.0.0/NEWS#L4) (StackStorm-Exchange/stackstorm-nexus3#1)

Fix a few things

---

.circle/requirements-dev.txt

This pull request updates lint dependency versions (flake8, pylint) so they match versions used in StackStorm/st2 repo.
Those new versions might identify some new issues on new (weekly) CI runs which may need to be fixed for the builds to pass again.

Upgrade lint dependency versions so the match versions in StackStorm/st2 repo

---

.circle/deployment
.circle/index.py

This pull request updates generate index script so we now also include all the available versions for each pack in the index.json file.
This implementation utilizes Github API to retrieve all the available tags for a particular pack repo.

Include available versions for all the packs in the index

---

.circle/deployment
.circle/semver.py

This pull request fixes a bug inadvertently introduced in #72.
Index incorrectly started picking up old versions - https://github.com/StackStorm-Exchange/index/commit/f56625926604c37cd50cad6f19c1c91cf82dfa49.
The bug was related to the code re-org I did. I reorganized the code so we create version tags before we create the index.
As part of the tag creating process, we check out every tag (from newest to oldest). To fix the issue, we need to switch back to the latest commit (master) after processing the tag.

Fix index bug

---

.circle/dependencies

This PR tweaks the `dependencies` script to use environment variables to specify the branches of ST2 and lint-configs to checkout. I maintain reverse compatibility by using Bash magic (eg: variable references) to default to the `master` branch if the environment variables are not defined.
This is useful for when you are working on fixing failing pack CIs and you want to test out some changes to, for instance, [the `st2-run-pack-tests` script from the st2 repository](https://github.com/StackStorm/st2/pull/4790). This should make it easier and faster to test out changes to the CI scripts for failing packs.
Before this PR, you had to rerun a failed CircleCI workflow with SSH, SSH in, tweak the `dependencies` script yourself (or manually checkout a different branch of st2 or lint-configs), …

Configurable checkouts

---

.circle/Makefile
utils/git-changes-files
utils/git-changes-json
utils/git-changes-packs
utils/git-changes-py
utils/git-changes-yaml

Only the files that have changed are validated for PR CI runs, but for the weekly CI runs all files are checked.
The AWS pack has a _lot_ of actions. Like a lot a lot of actions. So when, during the weekly CI run, the `Makefile` gathered a list of all of the YAML files and then tried to evaluate that in a Bash `if [ ! $(CHANGED_YAML) ]` statement, the number of arguments exceeded Bash's maximum number of arguments and [the CI job failed](https://circleci.com/gh/StackStorm-Exchange/stackstorm-aws/339) (I set `FORCE_CHECK_ALL_FILES` to `true` so it would behave like the weekly CI runs).
Due to that, I had to change up how all of that was processed. It doesn't really make sense to me to have the `FORCE_CHECK_ALL_FILES` environment variable option in all of the `git-changes` sub-scripts, …

Change Makefile to handle reeeeeally long lists of files

---

utils/pack_content.py

`yaml.safe_load` doesn't accept a `loader` argument, but we should default to loading YAML safely.
Luckily, everywhere `ordered_load` was used already passed in `yaml.SafeLoader` to subclass, so this shouldn't break anything. This PR does allow users of `ordered_load` to use non-safe loader classes, but now all users of that function have to explicitly enable the unsafe behavior and safe loading is the default.
Tested with the stackstorm-git pack.

Default to subclassing yaml.SafeLoader

---

.circle/Makefile
.circle/test

Fix assignment of `FORCE_CHECK_ALL_FILES` variables, also do better at checking for empty and non-empty strings.
And finally, fix the assignments to the `GIT_BRANCH` and `PYTHON_VERSION` variables. The `GIT_BRANCH` assignment was broken because it displayed all of the available branches (with the active branch first). And the `PYTHON_VERSION` assignment was broken because `python --version` prints the Python version to stderr, not stdout, so `PYTHON_VERSION` was always empty.

Force check

---

.circle/Makefile

This pull request adds new simple ``.license-check`` target to Makefile which runs as part of "test" CI script and verifies pack directory contains ``LICENSE`` file with Apache 2.0 license text.
The plan in the future also is to add ASF 2.0 license headers to all the source files and a lint check which verifies all the files contain correct license headers.
Related to "issue" reported in https://forum.stackstorm.com/t/which-license-is-for-stackstorm-exchange-stackstorm-jira/897/3.

Add license check to the pack test script

---

.circle/exit_on_py2_checks
.circle/exit_on_py3_checks

Reverts #81 (and fixes a typo).
Also adds support for packs that do _not_ declare Python 2 support, like the very forward looking [stackstorm-fortinet](https://github.com/StackStorm-Exchange/stackstorm-fortinet/blob/master/pack.yaml#L12).

Turn off python3 checks

---

.circle/deploy.py
.circle/index.py
.circle/requirements-ci-ci.txt
.circle/semver.py
.circle/validate.py
.circleci/config.yml
utils/pack_content.py

Add some quick checks for this `ci` repo.
This is a good idea to begin with, but this is immediately valuable to ensure that all of the Python scripts work on both Python 2.7 and Python 3, because some of our packs use Python 3 to deploy. And that's a trend that will only accelerate as Python 2 usage drops off.

Add CI to ci repo

---

.circle/dependencies
.circle/index.py
.circle/test

* Update `.circle/index.py` to run with both Python 2 and Python 3
* Reorder `circle/index.py` imports
* Log the Python executable location (to make sure it's running from the proper virtualenv)
* Update `.circle/dependencies` script to run again (helps when rerunning CircleCI jobs with SSH)

Python 3 and other improvements

---

.circle/Makefile
.circle/dependencies
.circle/deployment
.circle/exit_on_py2_checks
.circle/exit_on_py3_checks
.circle/retry_on_failure.sh
.circle/test
.circleci/config.yml
tools/add_webhook_to_github_repo.sh
tools/reset_github_user_token_and_update_circleci.sh
tools/set_repo_description.sh
tools/split-packs.sh
tools/trigger_circle_ci_builds_for_all_packs.sh
utils/exchange-bootstrap.sh
utils/git-changes
utils/git-changes-directories
utils/git-changes-files
utils/git-changes-json
utils/git-changes-packs
utils/git-changes-py
utils/git-changes-yaml

As well as a few small cleanups, this PR also fixes the CI scripts and the `Makefile` to work on PRs that have very large numbers of changed files, like StackStorm-Exchange/stackstorm-aws#89.
This PR also fixes CI for this repository.
Related: #76

Small cleanup

---

.circle/Makefile
.circle/test

My PR here (https://github.com/StackStorm-Exchange/stackstorm-circle_ci/pull/8#issuecomment-614640449) seems to have uncovered a bug with unit tests not being ran when ``FORCE_CHECK_ALL_FILES`` is set (e.g. for master builds or weekly builds).
I have no idea how long has this been broken / not working correctly (could have been since the beginning).
This being broken basically means we didn't run any pack unit tests as part of our weekly builds (that's obviously bad and it means we likely missed a bunch of failures).

Make sure we run unit tests if FORCE_CHECK_ALL_FILES is true

---

.circle/Makefile

Unfortunately the napalm_logs and netbox packs are not licensed under the Apache 2.0 License like the rest of the packs are.
I initiated [a PR](https://github.com/StackStorm-Exchange/stackstorm-netbox/pulls/17) to change the license, but we cannot do so without the consent of every contributor to those packs, and at this point I don't think we are going to get that from all contributors. Same story with the napalm_logs pack.
So, instead of checking for the Apache 2.0 license on those packs and failing every weekly CI run, we simply hardcode those two packs to exempt them from the Apache 2.0 License requirement. Luckily both are licensed under the very liberal MIT license, and were initially authored by John Anderson, so for those two packs we check for the MIT license instead.
I manually …

Check for the MIT license for the napalm_logs and netbox packs

---

.circle/requirements-dev.txt

With the new release of isort 5 that gets installed as a dependency of pylint, the pylint CI step is currently broken with the following error:
```
AttributeError: module 'isort' has no attribute 'SortImports'
```
This dependency issue is only fixed in newer pylint versions (>=2.4)

Fix pylint by locking isort module below version 5

---

tools/README.md
tools/copyright_update.py

I wrote this script to help me update the copyright headers in the StackStorm repo.
I'll use it in the future to also update copyrights across other repos including packs.

Added script for updating copyright headers

---

.circle/index.py
tools/reset_github_user_token_and_update_circleci.sh

When packs on Exchange fail to deploy, we don't have any good ways of detecting that failure and exiting gracefully with an informative or useful error message. On top of that, we don't point TSC members to the PAT tools in this `ci` repo, nor do we mention that the required credentials are in LastPass. And then on top of that, the reset token script tries to silently read environment variables.
This PR improves this entire situation, by "closing the loop" and laying down a trail of breadcrumbs for uninitiated users, both community members and TSC members.
First, it asks the user for the GitHub username and password, and then asks for the CircleCI token. If any of those are specified in environment variables, it silently uses those and skips asking the user for them. When the script asks …

Improve deployment scripts

---

.circle/dependencies

Fixes the following build error in StackStorm-Exchange during the pip install st2/requirements.txt
```
Modules/constants.h:7:10: fatal error: lber.h: No such file or directory
#include "lber.h"
^~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
----------------------------------------
```
Example failure: https://app.circleci.com/pipelines/github/StackStorm-Exchange/stackstorm-jmx/39/workflows/4c5d22d5-64a5-4ab8-9c31-0e97f620813a/jobs/247

Fix CI build missing new LDAP package dependency

---

.circle/test

A previous commit tried to use an empty string in a Bash `if` statement, but Bash doesn't work that way.
This PR tweaks that line to use Bash's `[[` builtin test function in the `if` statement.
This should help us avoid error messages like:
```
/home/circleci/ci/.circle/test: line 42: : command not found
```
in pack CI tests.
The tests still complete just fine, but that error could be a red herring for people investigating pack CI failures.

Use bash [[ builtin to test for nonempty variable

---

.circle/circle.yml.sample

StackStorm 3.3 is the last version to support 2.7. So, use the v3.3
branch instead of the master branch for the python 2.7 tests.

pin python2.7 tests to st2 3.3

---

.circle/circle.yml.sample
.circle/dependencies
.circle/deployment
.circle/index.py
.circle/install_gh

This adjusts the index regeneration so that it retrieves the list of all
pack versions (repo tags) in as few API calls as possible.
At 1 call per pack per pack deployment, multiple pack deployments can
easily hit the rate limit. Using graphql reduces the number of calls
that count toward the rate limit (today) to 2 per pack deployment.
Tags are apparently a very inexpensive API request, so github is only
counting 1 call per page. More complex queries can count as more than
one call per page, so this is very fortunate for our use case.
Graphql limits each page to 100 results, so with about 160 packs, that
is only 2 pages. So, we won't hit a 3rd page until we get over 200
packs.

Use Github graphql api to avoid rate limiting

---

.circle/dependencies

PATs expire when unused for a year: https://github.community/t/api-access-token-expiry/14522
So, we need to use it regularly. Adding an API hit to the weekly test run should keep the PAT active indefinitely.
Here we use the dependencies script so that it runs as early as possible each week before most other things might fail and kill the build.
Also, we use `|| true` so that any PR runs can continue passing even if the PAT has expired.

Use PATs weekly to prevent expiration

---

.circle/deployment
.circle/index.py
tools/functions.sh

- Fix support for non-master default pack branches
If any packs end up using `main` instead of `master` as their default
branch, then deploying the index will fail without this change.
Currently only the `test` and `test2` packs use an non-master default
branch (`aaa`). So, the impact of this change is minimal.
- Provide PAT error message as early as possible
Resolves #109 by printing a helpful error message much sooner if a PAT has expired.
- Add `DO_NOT_ADD_TO_EXCHANGE_INDEX` for CI packs
This variable should be set to `true` (a string, not a boolean)
in CircleCI's web UI for each test pack. This way, such test packs
can be used to test everything in the CI workflows including
changes to the `deploy` step's `deployment` script.

[BUGFIX] Fix support for non-master default branch in packs

---

.circle/circle.yml.sample

We will no longer test packs with python2.7, as it is broken and the fix
(re-adding 2.7) is too invasive across all of our infrastructure.
We continue supporting 2.7 but only on an as-reported basis.
If someone submits a PR for 2.7 and it doesn't break with python 3, great.
If a pack is upgraded so that it can only be used with python 3,
then people can downgrade to an earlier version that supported python 2.

Test infra for py2.7 is broken. Drop it.

---

.circleci/config.yml

There is no need to continue testing the files in this repo with python2.7.
This is a separate concern from #111 which drop testing packs with python2.7.

Drop Python2.7 for CI-testing CI

---

.circle/Makefile
.circle/dependencies
.circleci/config.yml

The pack CI is currently pinning `pip>=9.0,<9.1` in the `Makefile` and the `dependencies` script, both of which are used for pack CI (it is also pinned in the circleci config for this repo).
But, core st2 has `pip==20.0.2` pinned in its [`Makefile`](https://github.com/StackStorm/st2/blob/v3.3/Makefile#L56), which is also used by the `dependencies` script for pack CI.
```Makefile
PIP_VERSION ?= 20.0.2
```
And, to make the pinned versions even more problematic, `virtualenv` is now installing an even newer version of `pip` just before we try to install the st2 requirements, and that newer pip version (20.3) uses the new pip resolver which can't handle st2 requirements. This is the output of `virtualenv` in [a recent test run]( https://app.circleci.com/pipelines/github/StackStorm-Exchange/stac …

[BUGFIX] Pin the same pip version as core st2

---

.circle/circle.yml.sample
.circle/dependencies
.circle/setup_testing_env.sh.sample
utils/exchange-bootstrap.sh

I need some additional setup to run tests in the StackStorm-Exchange/stackstorm-vault#19.
This adds running the custom testing env setup script to the `dependencies` script.
It also adds a sample (empty) script and bootstraps new packs with it.

Custom pack deps script

---

utils/exchange-bootstrap.sh

GitHub and CircleCI broke their APIs.
GitHub doesn't allow us to create PATs anymore via the API, so we need to do that manually. I added a new environment variable `GITHUB_PACK_APT` that is checked and a helpful error message is output.
Also, for whatever reason the CircleCI API for following repos keeps returning 400 Bad Request. I've created a support ticket with them, so we'll see where that goes. It doesn't appear to affect anything as the project shows as "followed" by the stackstorm-neptr user.
On CircleCI i switched over to using their `Circle-Token` header instead of deprecated (no longer working) URL query parameter.

Fixing exchange bootstrap script with new GitHub and CircleCI api changes

---

.circle/deployment

The basic logic of the `deployment` script is:
1. get the list of commit hashes that modified `pack.yaml`
2. loop through each of those commit hashes
- check out `pack.yaml` from that commit
- if the version tag listed in `pack.yaml` is missing, tag the commit and push the tag
3. checkout `master` branch again (or whichever branch is default)
4. prepare/push the exchange index update
The checkout can become dirty in step 2 (see below).
This PR fixes step 3, by adding `--force` to the `git checkout` so it doesn't die if the checkout is dirty.
The checkout might be unclean if a script fails to parse old pack.yaml files.
This happens, for example, with the test pack. The test pack moved from version `0.3` to version `0.3.0` when semantic versioning was introduced/enforced. But `0.3` is not a …

Fix deployment if git checkout becomes unclean

---

.github/actions/checkout/action.yaml
.github/actions/py-dependencies/action.yaml
.github/actions/test/action.yaml
.github/workflows/pack-build_and_test.yaml

- set FORCE_CHECK_ALL_FILES=true by default (see #88)
- do not obscure the pip output with `pip -q`. Instead we can use gha output groups to jump past it.
- if a different branch of st2 or lint-configs is selected, then we need more than just one commit (`fetch-depth: 1`). So, if the branch is set to anything other than the default branch (`master`) then set `fetch-depth: 0` so that all history gets included.
Tested at https://github.com/StackStorm-Exchange/stackstorm-test/runs/4644706724

gha: cleanups

---

.github/workflows/index-update.yaml
.github/workflows/pack-bootstrap_repo.yaml
.github/workflows/pack-build_and_test.yaml
.github/workflows/pack-repo_meta.yaml
.github/workflows/pack-tag_release.yaml

This mirrors StackStorm/st2#5832 and fixes the index builds that have been failing.
See: https://github.com/StackStorm-Exchange/index/actions

pin GHA runners to ubuntu-20.04

---

.github/workflows/enable-pack-build-and-test.yaml

Might address [this](https://github.com/StackStorm-Exchange/ci/pull/137#issuecomment-1358864596) in #137.

Conditionally self-enable "Pack Build and Test" workflow

---

.github/workflows/enable-pack-build-and-test.yaml

This simplifies the workflow based on my comment here: https://github.com/StackStorm-Exchange/ci/pull/139#issuecomment-1360800869
> Cloning repos can be occassionally flaky. For the index, that's not an issue because we do it so often, that waiting a few more minutes for the next run doesn't really matter. For this workflow, I would like to avoid cloning the pack repos somehow, so that this can be more reliable.
And it switches from `gh workflow` to `gh api` so that we can use fine-grained PATs.

Enable pack "Build and Test" workflow without cloning && enable using fine-grained PAT

---

.github/actions/pack-meta/action.yaml
.github/workflows/pack-build_and_test.yaml

Ensure `CHANGES.md` or `CHANGELOG.md` and `pack.yaml` has been updated; in addition, ensure that the proposed pack version in `pack.yaml` is higher.
Here are some example runs in my forks and branches:
- [`CHANGES.md` or `CHANGELOG.md` not updated](https://github.com/mamercad/stackstorm-test-pack/actions/runs/3742313106)
- [`pack.yaml` not updated](https://github.com/mamercad/stackstorm-test-pack/actions/runs/3742331784)
- [Proposed pack version equal](https://github.com/mamercad/stackstorm-test-pack/actions/runs/3742342955)
- [Proposed pack version lower](https://github.com/mamercad/stackstorm-test-pack/actions/runs/3742359747)
- [All checks passing](https://github.com/mamercad/stackstorm-test-pack/actions/runs/3742361691)
Fixes #134.

CI: Pack metadata validation

---

.github/actions/extract-pack-meta/action.yaml
.github/actions/py-dependencies/action.yaml
.github/actions/test/action.yaml
.github/workflows/pack-bootstrap_repo.yaml

Github deprecated using the `::set-output` command in workflows/actions. Instead, we are supposed to use a environment file at `${GITHUB_OUTPUT}`.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

replace deprecated `::set-output` w/ `${GITHUB_OUTPUT}`

---

.github/actions/py-dependencies/action.yaml
.github/actions/py-dependencies/requirements-pack-tests.txt

The `Install CI Requirements` step for pack testing checks all packages in `requirements-dev.txt requirements-pack-tests.txt` found in this repo for a corresponding package in the `st2/test-requirements.txt` if there is a match, then the package will be installed. 
Due to the version of pytest being installed in `st2/requirements.txt` (7.0.1) additional pytest helper packages need to be installed to enable the `--cov` and other flags. These were being skipped because they were not called out in the above `requirements-dev.txt requirements-pack-tests.txt` files.
After adding the packages, an issue with the regex was not accounting for packages that were installing sub dependencies using `package-name[dependency]`, these packages would be skipped as the `[dependency]` would be read as a …

Install pytest helper packages for pack testing
